## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

Contains Labs 6 through 10: 8 Finding Duplicates, 9 Removing Duplicates, 6 Finding Missing Values, 7 Imputing Missing Values, and 10 Normalizing Dat

<hr>

Import pandas module.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('m1_survey_data.csv')
df.head(5)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy

In [3]:
df.shape

(11552, 85)

## Finding duplicates

In this section you will identify duplicate values in the dataset.

Find how many duplicate rows exist in the dataframe.

In [4]:
print('There are', df.duplicated().sum(), 'duplicate rows.')
print('There are', df.duplicated('Respondent').sum(), 'duplicate Respondants.')

There are 154 duplicate rows.
There are 154 duplicate Respondants.

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [5]:
df.drop_duplicates(inplace=True)
df.shape

(11398, 85)

Verify if duplicates were actually dropped.

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [6]:
print('There are now', df.duplicated().sum(), 'duplicate rows.')
print('There are', df.duplicated('Respondent').sum(), 'duplicate Respondants.')

There are now 0 duplicate rows.
There are 0 duplicate Respondants.

## Finding Missing values
Find the missing values for all columns.

In [7]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(df.isnull().sum())

Respondent                   0
MainBranch                   0
Hobbyist                     0
OpenSourcer                  0
OpenSource                  81
Employment                   0
Country                      0
Student                     51
EdLevel                    112
UndergradMajor             737
EduOther                   164
OrgSize                     96
DevType                     65
YearsCode                    9
Age1stCode                  13
YearsCodePro                16
CareerSat                    0
JobSat                       1
MgrIdiot                   493
MgrMoney                   497
MgrWant                    493
JobSeek                      0
LastHireDate                 0
LastInt                    413
FizzBuzz                    37
JobFactors                   3
ResumeUpdate                39
CurrencySymbol               0
CurrencyDesc                 0
CompTotal                  809
CompFreq                   206
ConvertedComp              816
WorkWeekHrs                122
WorkPlan                   121
WorkChallenge              164
WorkRemote                   8
WorkLoc                     32
ImpSyn                       5
CodeRev                      1
CodeRevHrs                2426
UnitTests                   29
PurchaseHow                196
PurchaseWhat                38
LanguageWorkedWith          11
LanguageDesireNextYear     134
DatabaseWorkedWith         453
DatabaseDesireNextYear    1042
PlatformWorkedWith         411
PlatformDesireNextYear     544
WebFrameWorkedWith        1393
WebFrameDesireNextYear    1617
MiscTechWorkedWith        2182
MiscTechDesireNextYear    1455
DevEnviron                  29
OpSys                       34
Containers                  82
BlockchainOrg             2322
BlockchainIs              2610
BetterLife                  98
ITperson                    35
OffOn                       38
SocialMedia                293
Extraversion                20
ScreenName                 507
SOVisit1st                 325
SOVisitFreq                  5
SOVisitTo                    1
SOFindAnswer                 3
SOTimeSaved                 50
SOHowMuchTime             1917
SOAccount                    1
SOPartFreq                1128
SOJobs                       6
EntTeams                     5
SOComm                       0
WelcomeChange               85
SONewContent              1965
Age                        287
Gender                      73
Trans                      123
Sexuality                  542
Ethnicity                  675
Dependents                 140
SurveyLength                19
SurveyEase                  14
dtype: int64

## Find out how many rows are missing in the column 'WorkLoc'

In [8]:
print("There are", df['WorkLoc'].isnull().sum(), "missing values in the column 'WorkLoc'")
print("There are", df['EdLevel'].isnull().sum(), "missing values in the column 'EdLevel'")
print("There are", df['Country'].isnull().sum(), "missing values in the column 'Country'")

There are 32 missing values in the column 'WorkLoc'
There are 112 missing values in the column 'EdLevel'
There are 0 missing values in the column 'Country'

## Imputing missing values


Find the value counts for the column WorkLoc.

In [10]:
print('There are', df['WorkLoc'].nunique(), 'unique Work Locations in the survey:')

print('\nWorkLoc  value count')      
print('-------                                    -----------')
print(df['WorkLoc'].value_counts())

print('\n\nThere are', df['Employment'].nunique(), 'unique Employment values in the survey:')

print('\nEmployment        value count')      
print('----------        -----------')
print(df['Employment'].value_counts())

print('\n\nThere are', df['UndergradMajor'].nunique(), 'unique UndergradMajor values in the survey:')

print('\nUndergradMajor        value count')      
print('---------------        -----------')
print(df['UndergradMajor'].value_counts())

There are 3 unique Work Locations in the survey:

WorkLoc  value count
-------                                    -----------
Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64


There are 2 unique Employment values in the survey:

Employment        value count
----------        -----------
Employed full-time    10968
Employed part-time      430
Name: Employment, dtype: int64


There are 12 unique UndergradMajor values in the survey:

UndergradMajor        value count
---------------        -----------
Computer science, computer engineering, or software engineering          6953
Information systems, information technology, or system administration     794
Another engineering discipline (ex. civil, electrical, mechanical)        759
Web development or web design                                             410
A natural science (ex. biology, chemistry, physics)                       403
Mathematics or statistics                                                 372
A business discipline (ex. accounting, finance, marketing)                244
A social science (ex. anthropology, psychology, political science)        210
A humanities discipline (ex. literature, history, philosophy)             207
Fine arts or performing arts (ex. graphic design, music, studio art)      161
I never declared a major                                                  124
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

## Identify the value that is most frequent (majority) in the WorkLoc column.

In [11]:
print(df['ConvertedComp'].mean())
print(df['ConvertedComp'].median())

131596.7316197316
57745.0



Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [12]:
import numpy as np

workloc_highest = 'Office'

missing_data = df.isnull()
#print(missing_data.head(5))

print('\nValue counts for missing data in WorkLoc:\n')
print( missing_data['WorkLoc'].value_counts())

Value counts for missing data in WorkLoc:

False    11366
True        32
Name: WorkLoc, dtype: int64

In [13]:
print('\nHere are the first 10 rows missing values for WorkLoc:')
print(df[missing_data['WorkLoc']][['Respondent','WorkLoc']].head(10))

df['WorkLoc'].replace(np.nan, workloc_highest, inplace=True)

Here are the first 10 rows missing values for WorkLoc:
      Respondent WorkLoc
130          285     NaN
242          550     NaN
866         1847     NaN
1455        2826     NaN
1753        3536     NaN
2339        4768     NaN
2689        5562     NaN
2788        5769     NaN
3165        6613     NaN
3213        6721     NaN

In [14]:
print('\nNew value counts for missing data in WorkLoc:\n')
print(missing_data['WorkLoc'].value_counts())

New value counts for missing data in WorkLoc:

False    11366
True        32
Name: WorkLoc, dtype: int64

## Normalizing data



There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

## List out the various categories in the column 'CompFreq'

In [15]:
print(df['CompFreq'].value_counts())

Yearly     6073
Monthly    4788
Weekly      331
Name: CompFreq, dtype: int64



Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

In [17]:
df.loc[df['CompFreq'] == 'Yearly', 'NormalizedAnnualCompensation']  = 1  * df['CompTotal']
df.loc[df['CompFreq'] == 'Monthly', 'NormalizedAnnualCompensation'] = 12 * df['CompTotal']
df.loc[df['CompFreq'] == 'Weekly', 'NormalizedAnnualCompensation']  = 52 * df['CompTotal']


df[['CompTotal','CompFreq','NormalizedAnnualCompensation']].head(20)

    CompTotal CompFreq  NormalizedAnnualCompensation
0     61000.0   Yearly                       61000.0
1    138000.0   Yearly                      138000.0
2     90000.0   Yearly                       90000.0
3     29000.0  Monthly                      348000.0
4     90000.0   Yearly                       90000.0
5      9500.0  Monthly                      114000.0
6      3000.0  Monthly                       36000.0
7    103000.0   Yearly                      103000.0
8     69000.0   Yearly                       69000.0
9      8000.0  Monthly                       96000.0
10     7000.0  Monthly                       84000.0
11   114000.0   Yearly                      114000.0
12     2000.0   Weekly                      104000.0
13    22000.0   Weekly                     1144000.0
14    96000.0  Monthly                     1152000.0
15   156000.0   Yearly                      156000.0
16    18000.0   Yearly                       18000.0
17     6400.0  Monthly                       76800.0
18     5000.0  Monthly                       60000.0
19   400000.0   Yearly                      400000.0

In [18]:
df['NormalizedAnnualCompensation'].median()

100000.0

In [20]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase,NormalizedAnnualCompensation
0,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy,61000.0
1,9,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,New Zealand,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,NaN,23.0,Man,No,Bisexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,138000.0
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Cour...,28.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy,90000.0
3,16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult,348000.0
4,17,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Australia,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;Multiracial,No,Appropriate in length,Easy,90000.0

In [21]:
df.isnull().sum()

Respondent                        0
MainBranch                        0
Hobbyist                          0
OpenSourcer                       0
OpenSource                       81
                               ...
Ethnicity                       675
Dependents                      140
SurveyLength                     19
SurveyEase                       14
NormalizedAnnualCompensation    815
Length: 86, dtype: int64

In [26]:
# Drop All Columns with Any Missing Value
df= df.dropna(axis=1)

In [27]:
df.isnull().sum()

Respondent        0
MainBranch        0
Hobbyist          0
OpenSourcer       0
Employment        0
Country           0
CareerSat         0
JobSeek           0
LastHireDate      0
CurrencySymbol    0
CurrencyDesc      0
WorkLoc           0
SOComm            0
dtype: int64

In [28]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
11547    False
11548    False
11549    False
11550    False
11551    False
Length: 11398, dtype: bool

In [29]:
# some imports to set up plotting
import matplotlib.pyplot as plt
# pip install seaborn
import seaborn as sns

In [30]:
print(df.shape)

(11398, 13)

In [31]:
print(df.columns)

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'Employment',
       'Country', 'CareerSat', 'JobSeek', 'LastHireDate', 'CurrencySymbol',
       'CurrencyDesc', 'WorkLoc', 'SOComm'],
      dtype='object')

In [32]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11398 entries, 0 to 11551
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Respondent      11398 non-null  int64
 1   MainBranch      11398 non-null  object
 2   Hobbyist        11398 non-null  object
 3   OpenSourcer     11398 non-null  object
 4   Employment      11398 non-null  object
 5   Country         11398 non-null  object
 6   CareerSat       11398 non-null  object
 7   JobSeek         11398 non-null  object
 8   LastHireDate    11398 non-null  object
 9   CurrencySymbol  11398 non-null  object
 10  CurrencyDesc    11398 non-null  object
 11  WorkLoc         11398 non-null  object
 12  SOComm          11398 non-null  object
dtypes: int64(1), object(12)
memory usage: 1.5+ MB
None

In [33]:
df.describe()

         Respondent
count  11398.000000
mean   12490.392437
std     7235.461999
min        4.000000
25%     6264.250000
50%    12484.000000
75%    18784.750000
max    25142.000000

In [35]:
df.head(3)

,Respondent,MainBranch,Hobbyist,OpenSourcer,Employment,Country,CareerSat,JobSeek,LastHireDate,CurrencySymbol,CurrencyDesc,WorkLoc,SOComm
0,4,I am a developer by profession,No,Never,Employed full-time,United States,Very satisfied,I am not interested in new job opportunities,Less than a year ago,USD,United States dollar,Home,"No, not really"
1,9,I am a developer by profession,Yes,Once a month or more often,Employed full-time,New Zealand,Slightly satisfied,"I’m not actively looking, but I am open to new...",Less than a year ago,NZD,New Zealand dollar,Office,"Yes, somewhat"
2,13,I am a developer by profession,Yes,Less than once a month but more than once per ...,Employed full-time,United States,Very satisfied,I am not interested in new job opportunities,3-4 years ago,USD,United States dollar,Home,Neutral

## Employe by Country

In [36]:
df["Country"].value_counts()

United States        3127
India                 897
United Kingdom        821
Germany               708
Canada                432
                     ...
Liechtenstein           1
Rwanda                  1
Brunei Darussalam       1
Cape Verde              1
Iraq                    1
Name: Country, Length: 135, dtype: int64

In [45]:
df["MainBranch"].value_counts()

I am a developer by profession                                                   10618
I am not primarily a developer, but I write code sometimes as part of my work      780
Name: MainBranch, dtype: int64